//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELDTestDataGenerator.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ELDTestDataEntities : DbContext
    {
        public ELDTestDataEntities()
            : base("name=ELDTestDataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<CountryState> CountryStates { get; set; }
        public virtual DbSet<EventRecordOrigin> EventRecordOrigins { get; set; }
        public virtual DbSet<EventRecordStatu> EventRecordStatus { get; set; }
        public virtual DbSet<EventStatu> EventStatus { get; set; }
        public virtual DbSet<EventType> EventTypes { get; set; }
        public virtual DbSet<TimeZone> TimeZones { get; set; }
        public virtual DbSet<Action> Actions { get; set; }
        public virtual DbSet<TestProfile> TestProfiles { get; set; }
        public virtual DbSet<TestProfileSegment> TestProfileSegments { get; set; }
    }
}
