//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELDTestDataGenerator.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestProfile
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TestProfile()
        {
            this.TestProfileSegments = new HashSet<TestProfileSegment>();
        }
    
        public string ProfileId { get; set; }
        public string ProfileName { get; set; }
        public Nullable<int> PollingIntervalSeconds { get; set; }
        public Nullable<System.DateTimeOffset> StartingDateTime { get; set; }
        public Nullable<double> StartingEngineHours { get; set; }
        public Nullable<int> StartingOdometer { get; set; }
        public string CarrierUSDOTNumber { get; set; }
        public string BluetoothId { get; set; }
        public string CMVUnitNumber { get; set; }
        public string CMVTrailerNumbers { get; set; }
        public string ShippingDocumentNumber { get; set; }
        public string VIN { get; set; }
        public string CarrierMultiDayBasis { get; set; }
        public string DeviceId { get; set; }
        public string CurrentDriverId { get; set; }
        public string Driver1Id { get; set; }
        public string Driver1FirstName { get; set; }
        public string Driver1LastName { get; set; }
        public bool Driver1IsExempt { get; set; }
        public Nullable<int> Driver1DayStartHour { get; set; }
        public string Driver1DriverLicenseIssuingStateCode { get; set; }
        public string Driver1DriverLicenseNumber { get; set; }
        public bool Driver1PersonalUseOfCMVAllowed { get; set; }
        public bool Driver1YardMovesAllowed { get; set; }
        public string Driver1TimeZoneId { get; set; }
        public string Driver2Id { get; set; }
        public string Driver2FirstName { get; set; }
        public string Driver2LastName { get; set; }
        public bool Driver2IsExempt { get; set; }
        public Nullable<int> Driver2DayStartHour { get; set; }
        public string Driver2DriverLicenseIssuingStateCode { get; set; }
        public string Driver2DriverLicenseNumber { get; set; }
        public bool Driver2YardMovesAllowed { get; set; }
        public bool Driver2PersonalUseOfCMVAllowed { get; set; }
        public string Driver2TimeZoneId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TestProfileSegment> TestProfileSegments { get; set; }
    }
}
