//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELDTestDataGenerator.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestProfileSegment
    {
        public int Id { get; set; }
        public string ProfileId { get; set; }
        public int SegmentSeqNum { get; set; }
        public string ActionId { get; set; }
        public string CommentAnnotation { get; set; }
        public Nullable<System.DateTime> DateOfCertifiedRecord { get; set; }
        public string DriversLocationDesc { get; set; }
        public Nullable<int> DurationSeconds { get; set; }
        public Nullable<int> MPH { get; set; }
    
        public virtual TestProfile TestProfile { get; set; }
    }
}
